---
- hosts: all
  become: true
  tasks:
    - name: Install httpd package
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Ensure httpd service is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
