---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.package:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure DOkcerservice is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"
