name: Test pipeline

on:
  push:
    branches:
    - master

jobs:
  initial_job:
    runs-on: ubuntu-latest

    steps:
    - name: First step
      run: |
        echo First
        echo Two
        echo three >> three.txt
    - name: Read file
      run: cat three.txt
